---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-sa-token"
          key: "PROMETHEUS_TOKEN"
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      # Adjust it based on ServiceMonitor configuration
      # Defeault OpenShift scrape_interval: 30s
      timeInterval: 30s
      tlsSkipVerify: true
    name: prometheus
    secureJsonData:
      httpHeaderValue1: "Bearer ${PROMETHEUS_TOKEN}"
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0