{
 "title": "Morpheus agent",
 "description": "Dashboard for Morpheus client",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{job=\"agent-morpheus-client\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", job=\"agent-morpheus-client\"}"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status!~\"5..\", namespace=\"$namespace\"}[2m]))\n/\nsum(rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "description": "Statistics for In-Memory queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "morpheus_request_queue_config_max_size{namespace=\"$namespace\"}",
     "legendFormat": "QueueMaxSize"
    },
    {
     "expr": "morpheus_request_queue_active{namespace=\"$namespace\"}",
     "legendFormat": "ActiveQueueSize"
    },
    {
     "expr": "morpheus_request_queue_pending{namespace=\"$namespace\"}",
     "legendFormat": "PendingQueueSize"
    }
   ]
  },
  {
   "title": "Reports insight",
   "type": "timeseries",
   "description": "Rate of reports with a concrete positive result of analysis (not uncertain or insufficient_intel)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "morpheus_rate_of_successful_reports{namespace=\"$namespace\"}",
     "legendFormat": "Successful reports"
    },
    {
     "expr": "morpheus_rate_of_successful_results{namespace=\"$namespace\"}",
     "legendFormat": "Successful results"
    }
   ]
  },
  {
   "title": "Reports state",
   "type": "timeseries",
   "description": "Reports by state (failed, expired, completed, sent, queued)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"morpheus_reports_state_.*_total\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Justification labels",
   "type": "timeseries",
   "description": "Counter of reports returned with all available labels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"morpheus_results_label_.*_count_operations\", namespace=\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Edpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Total number of requests (by endpoint)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[2m])) by (uri)",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Maximum inbound request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_max) by (uri)",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Average inbound request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{namespace=\"$namespace\"}[2m]) / rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Sum of the duration of every request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{namespace=\"$namespace\"}[2m])",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sysadmin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{namespace=\"$namespace\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{namespace=\"$namespace\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{namespace=\"$namespace\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{namespace=\"$namespace\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{namespace=\"$namespace\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{namespace=\"$namespace\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"heap\",namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",namespace=\"$namespace\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{area=\"heap\",namespace=\"$namespace\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\",namespace=\"$namespace\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",namespace=\"$namespace\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{namespace=\"$namespace\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{namespace=\"$namespace\"}",
       "legendFormat": "cpus"
      }
     ]
    }
   ]
  }
 ]
}